/**
 * Full-track waveform peaks — the machine reads the whole song at once.
 *
 * Radio tracks ship with build-time peaks (audiowaveform-compatible JSON,
 * generated by scripts/generate-peaks.py); dropped files get the identical
 * reduction computed in-browser off decodeAudioData. Either way the deck
 * strip knows the entire track the moment it starts: the drop is visible
 * before it arrives, the strip becomes a scrubber, and the instrument can
 * arm itself for what's coming.
 */

export interface TrackPeaks {
  /** Normalized 0..1 amplitude per overview pixel. */
  amp: Float32Array
  /** Seconds of audio each entry covers. */
  secondsPerPixel: number
}

interface AWFJson {
  sample_rate: number
  samples_per_pixel: number
  length: number
  data: number[]
  bits: number
}

/** Build-time peaks for a radio track ('/tracks/foo.mp3' → '/peaks/foo.json'). */
export async function loadPeaks(src: string): Promise<TrackPeaks | null> {
  const m = src.match(/\/(tracks|tracks-local)\/(.+)\.[^.]+$/)
  if (!m) return null
  try {
    const base = import.meta.env.BASE_URL
    const r = await fetch(`${base}${m[1] === 'tracks-local' ? 'peaks-local' : 'peaks'}/${m[2]}.json`)
    if (!r.ok) return null
    const j = (await r.json()) as AWFJson
    const n = j.length
    const amp = new Float32Array(n)
    const scale = j.bits === 8 ? 127 : 32767
    for (let i = 0; i < n; i++) {
      // Interleaved min/max pairs; amplitude = the larger excursion.
      amp[i] = Math.max(Math.abs(j.data[i * 2]), Math.abs(j.data[i * 2 + 1])) / scale
    }
    return { amp, secondsPerPixel: j.samples_per_pixel / j.sample_rate }
  } catch {
    return null
  }
}

/** The same reduction, computed live for a dropped file. */
export async function peaksFromFile(file: File, ctx: AudioContext): Promise<TrackPeaks | null> {
  try {
    const buf = await ctx.decodeAudioData(await file.arrayBuffer())
    const ch = buf.getChannelData(0)
    const spp = Math.round(buf.sampleRate / 20) // 20 px/second, same as build-time
    const n = Math.floor(ch.length / spp)
    const amp = new Float32Array(n)
    for (let i = 0; i < n; i++) {
      let m = 0
      const end = (i + 1) * spp
      for (let s = i * spp; s < end; s++) {
        const v = Math.abs(ch[s])
        if (v > m) m = v
      }
      amp[i] = m
    }
    return { amp, secondsPerPixel: spp / buf.sampleRate }
  } catch {
    return null
  }
}

/** Mean upcoming energy over the next `windowSec`, 0..1 — the pre-arm feed. */
export function energyAhead(p: TrackPeaks, progress: number, windowSec: number): number {
  const n = p.amp.length
  if (!n) return 0
  const i0 = Math.min(n - 1, Math.floor(progress * n))
  const i1 = Math.min(n, i0 + Math.max(1, Math.round(windowSec / p.secondsPerPixel)))
  let sum = 0
  for (let i = i0; i < i1; i++) sum += p.amp[i]
  return sum / Math.max(1, i1 - i0)
}
