/**
 * Full-track waveform peaks — the machine reads the whole song at once.
 *
 * Radio tracks ship with build-time peaks (audiowaveform-compatible JSON,
 * generated by scripts/generate-peaks.py); dropped files get the identical
 * reduction computed in-browser off decodeAudioData. Either way the deck
 * strip knows the entire track the moment it starts: the drop is visible
 * before it arrives, the strip becomes a scrubber, and the instrument can
 * arm itself for what's coming.
 */

export interface TrackPeaks {
  /** Normalized 0..1 amplitude per overview pixel. */
  amp: Float32Array
  /** Seconds of audio each entry covers. */
  secondsPerPixel: number
}

interface AWFJson {
  sample_rate: number
  samples_per_pixel: number
  length: number
  data: number[]
  bits: number
}

/** Build-time peaks for a radio track ('/tracks/foo.mp3' → '/peaks/foo.json'). */
export async function loadPeaks(src: string): Promise<TrackPeaks | null> {
  const m = src.match(/\/(tracks|tracks-local)\/(.+)\.[^.]+$/)
  if (!m) return null
  try {
    const base = import.meta.env.BASE_URL
    const r = await fetch(`${base}${m[1] === 'tracks-local' ? 'peaks-local' : 'peaks'}/${m[2]}.json`)
    if (!r.ok) return null
    const j = (await r.json()) as AWFJson
    const n = j.length
    const amp = new Float32Array(n)
    const scale = j.bits === 8 ? 127 : 32767
    for (let i = 0; i < n; i++) {
      // Interleaved min/max pairs; amplitude = the larger excursion.
      amp[i] = Math.max(Math.abs(j.data[i * 2]), Math.abs(j.data[i * 2 + 1])) / scale
    }
    return { amp, secondsPerPixel: j.samples_per_pixel / j.sample_rate }
  } catch {
    return null
  }
}

/** The same reduction, computed live for a dropped file. */
export async function peaksFromFile(file: File, ctx: AudioContext): Promise<TrackPeaks | null> {
  try {
    const buf = await ctx.decodeAudioData(await file.arrayBuffer())
    const ch = buf.getChannelData(0)
    const spp = Math.round(buf.sampleRate / 20) // 20 px/second, same as build-time
    const n = Math.floor(ch.length / spp)
    const amp = new Float32Array(n)
    for (let i = 0; i < n; i++) {
      let m = 0
      const end = (i + 1) * spp
      for (let s = i * spp; s < end; s++) {
        const v = Math.abs(ch[s])
        if (v > m) m = v
      }
      amp[i] = m
    }
    return { amp, secondsPerPixel: spp / buf.sampleRate }
  } catch {
    return null
  }
}

/**
 * The same reduction again, for a STREAMED radio track (Audius) -- which
 * ships no build-time peaks, so until this existed the radio never had a
 * drop forecast at all. The machine fetches the stream a second time in the
 * background, decodes it, and reads the whole song exactly as it reads a
 * dropped file. Until it lands there are no peaks, and the deck shows what
 * it shows with no peaks: nothing guessed (law 3).
 *
 * Off the critical path on purpose:
 *  · decoded by an OfflineAudioContext at PEAK_RATE, mono-downmixed --
 *    the build-time pass's own rate (scripts/generate-peaks.py), so a
 *    streamed track is read exactly as a shipped one is. Half the memory
 *    of a 44.1/48 kHz decode, and the resampling happens inside the
 *    decoder, not on the main thread. Lower was measured and refused:
 *    over the 22 shipped tracks, 22.05 kHz reproduces every build-time
 *    drop within 0.4s; 11 kHz misses two and invents one, 8 kHz misses
 *    three. A cheaper decode that reads the music wrong is not a saving.
 *  · the reduction loop yields to the main thread every slice, so even a
 *    ten-minute track never holds a frame.
 *  · capped: a stream larger than STREAM_MAX_BYTES, or not downloaded
 *    within STREAM_MAX_MS, is abandoned (no forecast, not a wrong one).
 *    STREAM_PROJECT_MS into each try, a download whose own measured rate
 *    says it cannot finish inside the cap is dropped right then and tried
 *    again on another content node (STREAM_ATTEMPTS in all): Audius
 *    redirects every stream to
 *    one of its nodes, and measured from here some serve ~5 MB/s, some
 *    ~500 KB/s, and some stall at a few KB for as long as you wait. The
 *    retry is what turns those last into a forecast instead of nothing;
 *    the early verdict is what keeps a dead node from costing the full
 *    cap. Measured over 24 radio tracks: 21 read (most in 2-5s, the
 *    retried ones in 10-24s), 3 refused after three slow nodes. A forecast
 *    that lands 15s in is still a forecast: the earliest drop findDrops
 *    reports is 12s in, and most land far later.
 *  · `signal` belongs to the track's peaks generation: a skip aborts the
 *    download or the decode mid-flight.
 *  · skipped outright when the visitor asked the browser to save data.
 *  · cached per track (memory, plus a small IndexedDB LRU), so a replay or
 *    a radio loop round never fetches the same song twice.
 */
const PEAK_RATE = 22050
const PEAK_PPS = 20 // pixels per second, same as build-time and peaksFromFile
const STREAM_MAX_BYTES = 25 * 1024 * 1024
const STREAM_MAX_MS = 25000
const STREAM_PROJECT_MS = 3000
const STREAM_ATTEMPTS = 3
const SLICE_SAMPLES = 400_000 // samples touched between yields: a few ms of work

/** Audius serves one track from several discovery hosts; key on the id. */
function streamKey(url: string): string {
  const m = url.match(/\/v1\/tracks\/([^/?#]+)\/stream/)
  return m ? `audius:${m[1]}` : url
}

const memCache = new Map<string, TrackPeaks>()
const MEM_MAX = 40
function memPut(key: string, p: TrackPeaks) {
  memCache.delete(key)
  memCache.set(key, p)
  while (memCache.size > MEM_MAX) memCache.delete(memCache.keys().next().value as string)
}

// IndexedDB LRU. Every touch is wrapped: private windows, blocked storage
// and quota errors all degrade to "not cached", never to a thrown error.
const IDB_NAME = 'scope-peaks'
const IDB_STORE = 'p'
const IDB_MAX = 60
interface IdbRow { key: string; at: number; spp: number; amp: Float32Array }
let dbP: Promise<IDBDatabase | null> | null = null
function idb(): Promise<IDBDatabase | null> {
  return (dbP ??= new Promise<IDBDatabase | null>((res) => {
    try {
      const rq = indexedDB.open(IDB_NAME, 1)
      rq.onupgradeneeded = () => {
        const s = rq.result.createObjectStore(IDB_STORE, { keyPath: 'key' })
        s.createIndex('at', 'at')
      }
      rq.onsuccess = () => res(rq.result)
      rq.onerror = () => res(null)
      rq.onblocked = () => res(null)
    } catch {
      res(null)
    }
  }))
}
async function idbGet(key: string): Promise<TrackPeaks | null> {
  const db = await idb()
  if (!db) return null
  return new Promise((res) => {
    try {
      const tx = db.transaction(IDB_STORE, 'readwrite')
      const s = tx.objectStore(IDB_STORE)
      const rq = s.get(key)
      rq.onsuccess = () => {
        const row = rq.result as IdbRow | undefined
        if (!row || !(row.amp instanceof Float32Array) || !(row.spp > 0)) return res(null)
        row.at = Date.now() // LRU touch
        s.put(row)
        res({ amp: row.amp, secondsPerPixel: row.spp })
      }
      rq.onerror = () => res(null)
    } catch {
      res(null)
    }
  })
}
async function idbPut(key: string, p: TrackPeaks): Promise<void> {
  const db = await idb()
  if (!db) return
  try {
    const tx = db.transaction(IDB_STORE, 'readwrite')
    const s = tx.objectStore(IDB_STORE)
    s.put({ key, at: Date.now(), spp: p.secondsPerPixel, amp: p.amp } satisfies IdbRow)
    const cnt = s.count()
    cnt.onsuccess = () => {
      let extra = cnt.result - IDB_MAX
      if (extra <= 0) return
      const cur = s.index('at').openCursor()
      cur.onsuccess = () => {
        const c = cur.result
        if (!c || extra-- <= 0) return
        c.delete()
        c.continue()
      }
    }
  } catch {
    /* not cached; the next play decodes again */
  }
}

const yieldToMain = () => new Promise<void>((r) => setTimeout(r, 0))

/** Stats from the last streamed decode -- read by the browser checks. */
export const streamPeaksStats: { key: string; bytes: number; fetchMs: number; decodeMs: number; reduceMs: number; from: string } =
  { key: '', bytes: 0, fetchMs: 0, decodeMs: 0, reduceMs: 0, from: '' }

type Got = { data: Uint8Array<ArrayBuffer>; bytes: number } | 'slow' | 'big' | null

/** Another try at the same track lands on another content node: Audius
 *  picks the node per redirect, and the redirect for the bare URL is
 *  edge-cached, so a retry with the same URL would meet the same slow node. */
function reroll(url: string, n: number): string {
  return /\/v1\/tracks\/[^/?#]+\/stream/.test(url) ? `${url}${url.includes('?') ? '&' : '?'}scope_try=${n}` : url
}

/** One download, watched. 'slow' when its own measured rate says it cannot
 *  finish by `endAt` (or nothing has arrived STREAM_PROJECT_MS in); 'big'
 *  past STREAM_MAX_BYTES; null when it failed or `outer` aborted it. */
async function downloadOnce(url: string, outer: AbortSignal, endAt: number): Promise<Got> {
  const ac = new AbortController()
  const onAbort = () => ac.abort()
  outer.addEventListener('abort', onAbort, { once: true })
  const t0 = performance.now()
  let bytes = 0
  let declared = 0
  let tFirst = 0
  let firstBytes = 0
  let slow = false
  // The rate is measured from the first byte, not from the request: the
  // redirect and the node's time-to-first-byte are paid once, and folding
  // them into the rate condemned nodes that were merely slow to start.
  const watch = setInterval(() => {
    const now = performance.now()
    let late = now > endAt
    if (!late && now - t0 > STREAM_PROJECT_MS) {
      // nothing at all, twice the grace: this node is not serving
      if (!bytes) late = now - t0 > 2 * STREAM_PROJECT_MS
      else if (declared && now - tFirst > 1000) {
        const rate = (bytes - firstBytes) / (now - tFirst)
        late = rate <= 0 || now + (declared - bytes) / rate > endAt
      }
    }
    if (late) {
      slow = true
      ac.abort()
    }
  }, 250)
  try {
    // no-store is not about freshness. The player is reading this exact
    // URL, and Chrome's HTTP cache lets one request per URL write at a
    // time: measured, a second plain fetch sat at zero bytes, no response
    // headers, until it was abandoned. Bypassing the cache bypasses the lock.
    const r = await fetch(url, { signal: ac.signal, mode: 'cors', credentials: 'omit', cache: 'no-store' })
    if (!r.ok || !r.body) return null
    declared = Number(r.headers.get('content-length') ?? 0)
    if (declared > STREAM_MAX_BYTES) return 'big'
    const reader = r.body.getReader()
    const chunks: Uint8Array[] = []
    for (;;) {
      const { done, value } = await reader.read()
      if (done) break
      if (!tFirst) {
        tFirst = performance.now()
        firstBytes = value.byteLength
      }
      bytes += value.byteLength
      if (bytes > STREAM_MAX_BYTES) return 'big'
      chunks.push(value)
    }
    const data = new Uint8Array(bytes)
    let o = 0
    for (const c of chunks) {
      data.set(c, o)
      o += c.byteLength
    }
    return { data, bytes }
  } catch {
    return slow && !outer.aborted ? 'slow' : null
  } finally {
    clearInterval(watch)
    outer.removeEventListener('abort', onAbort)
    ac.abort() // a 'big' return leaves the body unread; stop it downloading
  }
}

export async function peaksFromStream(url: string, signal: AbortSignal): Promise<TrackPeaks | null> {
  const key = streamKey(url)
  const hit = memCache.get(key)
  if (hit) {
    memPut(key, hit)
    Object.assign(streamPeaksStats, { key, bytes: 0, fetchMs: 0, decodeMs: 0, reduceMs: 0, from: 'mem' })
    return hit
  }
  const stored = await idbGet(key)
  if (signal.aborted) return null
  if (stored) {
    memPut(key, stored)
    Object.assign(streamPeaksStats, { key, bytes: 0, fetchMs: 0, decodeMs: 0, reduceMs: 0, from: 'idb' })
    return stored
  }
  // The visitor asked for less data: a second full download of the song
  // is exactly what they asked us not to do.
  const conn = (navigator as Navigator & { connection?: { saveData?: boolean } }).connection
  if (conn?.saveData) return null
  if (typeof OfflineAudioContext === 'undefined') return null

  const tStart = performance.now()
  const endAt = tStart + STREAM_MAX_MS
  let got: Got = null
  let tries = 0
  try {
    while (tries < STREAM_ATTEMPTS && !signal.aborted) {
      got = await downloadOnce(tries ? reroll(url, tries) : url, signal, endAt)
      tries++
      if (got !== 'slow') break
    }
    if (signal.aborted) return null
    if (!got || typeof got === 'string') {
      Object.assign(streamPeaksStats, { key, bytes: 0, fetchMs: 0, decodeMs: 0, reduceMs: 0, from: `refused: ${got === 'big' ? 'too large' : got === 'slow' ? 'too slow' : 'unreachable'} (${tries} tries)` })
      return null
    }
    const { data: whole, bytes } = got
    const fetchMs = performance.now() - tStart
    const t1 = performance.now()
    const oac = new OfflineAudioContext(1, 1, PEAK_RATE)
    const buf = await oac.decodeAudioData(whole.buffer)
    if (signal.aborted) return null
    const decodeMs = performance.now() - t1

    const t2 = performance.now()
    const chans: Float32Array[] = []
    for (let c = 0; c < buf.numberOfChannels; c++) chans.push(buf.getChannelData(c))
    const nc = chans.length
    const spp = Math.round(buf.sampleRate / PEAK_PPS)
    const n = Math.floor(buf.length / spp)
    const amp = new Float32Array(n)
    const pxPerSlice = Math.max(1, Math.floor(SLICE_SAMPLES / (spp * nc)))
    for (let i0 = 0; i0 < n; i0 += pxPerSlice) {
      const i1 = Math.min(n, i0 + pxPerSlice)
      for (let i = i0; i < i1; i++) {
        let m = 0
        const end = (i + 1) * spp
        for (let s = i * spp; s < end; s++) {
          // mono downmix, as the build-time ffmpeg pass does (-ac 1)
          let v = 0
          for (let c = 0; c < nc; c++) v += chans[c][s]
          v = Math.abs(v / nc)
          if (v > m) m = v
        }
        amp[i] = m
      }
      if (i1 < n) {
        await yieldToMain()
        if (signal.aborted) return null
      }
    }
    const p: TrackPeaks = { amp, secondsPerPixel: spp / buf.sampleRate }
    Object.assign(streamPeaksStats, { key, bytes, fetchMs, decodeMs, reduceMs: performance.now() - t2, from: tries > 1 ? `net (${tries} tries)` : 'net' })
    memPut(key, p)
    void idbPut(key, p)
    return p
  } catch {
    // undecodable: no forecast, and nothing to say about the music
    if (!signal.aborted) Object.assign(streamPeaksStats, { key, from: 'refused: will not decode' })
    return null
  }
}

/** Mean upcoming energy over the next `windowSec`, 0..1 — the pre-arm feed. */
export function energyAhead(p: TrackPeaks, progress: number, windowSec: number): number {
  const n = p.amp.length
  if (!n) return 0
  const i0 = Math.min(n - 1, Math.floor(progress * n))
  const i1 = Math.min(n, i0 + Math.max(1, Math.round(windowSec / p.secondsPerPixel)))
  let sum = 0
  for (let i = i0; i < i1; i++) sum += p.amp[i]
  return sum / Math.max(1, i1 - i0)
}

/**
 * Drop detection — "only real readings": a drop is a place where energy
 * rises sharply and stays up for a couple of seconds, right after a stretch
 * that was genuinely quiet *for this track* (not just quieter than the very
 * next beat). Three conditions all have to hold at once: the ~6s window
 * before is a real breakdown (well below the track's typical level), the
 * ~2s window after is genuinely loud (not just loud relative to near-silence),
 * and the jump between them is sharp. Requiring the breakdown is what keeps
 * a steady wall-to-wall track — which never dips — at zero or near-zero,
 * rather than firing on every strong beat.
 */
export interface Drop {
  /** Onset time, seconds. */
  t: number
  /** 0..1, how far the sustained jump cleared the detection threshold. */
  strength: number
}

const DROP_SHORT_SEC = 0.75 /** gap left between the baseline window and the point under test, so the baseline can't bleed into the rise it's being compared against */
const DROP_LONG_SEC = 6 /** baseline window: the build/breakdown right before it */
const DROP_SUSTAIN_SEC = 2 /** the jump must average this high for this long, not just spike */
const DROP_MIN_SPACING_SEC = 12 /** refuse a second drop this soon after one */
/** An intro's first kick isn't a drop. 5s let four of 22 library tracks
 *  report a "drop" at 6.7s -- the beat arriving after the intro, which the
 *  6s baseline window read as a breakdown. Real drops land later. */
const DROP_INTRO_SKIP_SEC = 12
const DROP_MIN_RATIO = 2.0 /** sustained/baseline energy ratio required to call it a sharp rise */
const DROP_BREAKDOWN_FRAC = 0.55 /** baseline must sit below this fraction of the track's typical (p60) energy — i.e. an actual quiet build, not just a normal bar */
const DROP_SUSTAIN_LEVEL_FRAC = 0.75 /** the rise itself must reach this fraction of the track's typical energy — i.e. actually loud, not just "loud for a quiet spot" */

/**
 * Compute once per track (not per frame): O(n) via a running energy prefix
 * sum, sorted once for per-track percentile normalisation (loudness varies
 * per track, so both the "is this a breakdown" and "is this loud" checks are
 * relative to that track's own energy distribution, not an absolute level).
 * Results are sorted by t.
 */
export function findDrops(p: TrackPeaks): Drop[] {
  const { amp, secondsPerPixel: s } = p
  const n = amp.length
  const drops: Drop[] = []
  if (n === 0 || s <= 0) return drops

  const shortWin = Math.max(1, Math.round(DROP_SHORT_SEC / s))
  const longWin = Math.max(shortWin, Math.round(DROP_LONG_SEC / s))
  const sustainWin = Math.max(1, Math.round(DROP_SUSTAIN_SEC / s))
  const minSpacing = Math.max(1, Math.round(DROP_MIN_SPACING_SEC / s))
  const introSkip = Math.round(DROP_INTRO_SKIP_SEC / s)
  const start = Math.max(introSkip, longWin + shortWin)
  if (start + sustainWin >= n) return drops

  // Running energy (amplitude^2) as a prefix sum, so any window's mean is O(1).
  const prefix = new Float64Array(n + 1)
  for (let i = 0; i < n; i++) prefix[i + 1] = prefix[i] + amp[i] * amp[i]
  const windowMean = (a: number, b: number) => (prefix[b] - prefix[Math.max(a, 0)]) / (b - a)

  // Per-track reference levels via a one-time sort of per-pixel energy:
  // p60 stands in for "how loud this track normally runs", p95 for "about
  // as loud as it gets" (used to scale strength 0..1).
  const energies = new Float32Array(n)
  for (let i = 0; i < n; i++) energies[i] = amp[i] * amp[i]
  const sorted = Array.from(energies).sort((a, b) => a - b)
  const pct = (q: number) => sorted[Math.min(sorted.length - 1, Math.floor(sorted.length * q))] ?? 0
  const trackTypical = pct(0.6)
  const trackPeak = pct(0.95)
  const eps = 1e-9

  let i = start
  while (i < n - sustainWin) {
    const longE = windowMean(i - shortWin - longWin, i - shortWin)
    const sustainE = windowMean(i, i + sustainWin)

    const isBreakdown = longE < DROP_BREAKDOWN_FRAC * trackTypical // quiet build before it
    const isLoudEnough = sustainE > DROP_SUSTAIN_LEVEL_FRAC * trackTypical // genuinely loud after, not just relatively so
    const isSharpRise = sustainE / (longE + eps) >= DROP_MIN_RATIO

    if (isBreakdown && isLoudEnough && isSharpRise) {
      const strength = Math.max(0, Math.min(1, (sustainE - longE) / Math.max(trackPeak - longE, eps)))
      drops.push({ t: i * s, strength })
      i += minSpacing
      continue
    }
    i++
  }
  return drops
}

/** First drop after `nowSec`, or null. O(log n), no allocations. */
export function nextDrop(drops: Drop[], nowSec: number): Drop | null {
  let lo = 0
  let hi = drops.length
  while (lo < hi) {
    const mid = (lo + hi) >>> 1
    if (drops[mid].t > nowSec) hi = mid
    else lo = mid + 1
  }
  return lo < drops.length ? drops[lo] : null
}
